#!/bin/bash
# Manual database setup commands
# Run this file or copy-paste the commands below

echo "==================================================================="
echo "Manual Database Setup for Washdb-Bot"
echo "==================================================================="
echo ""
echo "Copy and paste these commands into your terminal:"
echo ""
echo "# Switch to postgres user and create database"
echo "sudo -u postgres psql << 'EOF'"
echo ""
echo "-- Create user washbot"
echo "CREATE USER washbot WITH PASSWORD 'change_me_strong';"
echo ""
echo "-- Create database washdb"
echo "CREATE DATABASE washdb OWNER washbot;"
echo ""
echo "-- Grant privileges"
echo "GRANT ALL PRIVILEGES ON DATABASE washdb TO washbot;"
echo ""
echo "-- Connect to washdb and grant schema permissions"
echo "\c washdb"
echo "GRANT ALL ON SCHEMA public TO washbot;"
echo "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO washbot;"
echo "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO washbot;"
echo ""
echo "-- List databases to verify"
echo "\l washdb"
echo ""
echo "EOF"
echo ""
echo "==================================================================="
echo "After running the above, continue with:"
echo "  cd /home/rivercityscrape/URL-Scrape-Bot/washdb-bot"
echo "  source .venv/bin/activate"
echo "  python -m db.init_db"
echo "==================================================================="
